---
title: "Exercises for chapter x"
author: "team name"
date: "date"
output:
  html_document: 
    mathjax: default
    toc: true
    toc_depth: 2
header-includes: 
    \usepackage{xcolor}
    \usepackage{amsmath}
---

  
```{css, echo = F}
body{
  font-family: Helvetica;
  font-size: 16pt;
  max-width: 1000px;
  margin: auto;
  margin-left:310px;
}
pre{
  font-size: 14px;
}
/* Headers */
h1{
    font-size: 24pt;
  }
h1,h2{
    font-size: 20pt;
  }
h3,h4,h5,h6{
  font-size: 18pt;
}

#TOC {
  position: fixed;
  left: 0;
  top: 0;
  width: 300px;
  height: 100%;
  overflow:auto;
}
```

```{r setup, include=FALSE, message=FALSE, warning=FALSE, results='hide'}
knitr::opts_chunk$set(echo = TRUE, dpi = 300)

library(rethinking)
library(magrittr)
# add other packages you use here
```

# Header 1a

## Header 2a: An example equation


$$ 
y \sim normal(\bar \mu, \sigma)   \\ 
\bar \mu \sim normal(0,3)  \\ 
\sigma \sim exponential(1) \\
$$

# Header 1b

## Header 2b: Hide cluttered output from ulam

If you estimate models with `ulam` it is a good idea to do estimation and plotting of model results in separate code blocks.

Use a code block like a following to estimate the model:

```{r warning=FALSE, results='hide'}
n.cores = ifelse(Sys.info()["sysname"] == "Darwin",4,1)

my.fit = ulam(
  alist(
    y ~ dnorm(mu, sigma),
    mu ~ dnorm(0,3),
    sigma ~ dexp(2)
  ),
  data = list(y = rnorm(25)),
  log_lik = TRUE,
  chains = 4)
```

And do additional steps with the resulting fit object in the following code blocks:

```{r}
precis(my.fit)
```

```{r}
divergent(my.fit)
```



